
name: Render Remotion Video

on:
  repository_dispatch:
    types: [render-video]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Render Video with Remotion
        env:
          IMAGES: ${{ toJson(github.event.client_payload.images) }}
          AUDIO_URL: ${{ github.event.client_payload.audioUrl }}
          SUBTITLES: ${{ toJson(github.event.client_payload.subtitles) }}
          SUBTITLE_STYLE: ${{ github.event.client_payload.styleType }}
          TRANSITION_TYPE: ${{ github.event.client_payload.transitionType }}
        run: |
          echo "Rendering video with props:"
          echo "Images: $IMAGES"
          echo "Audio URL: $AUDIO_URL"
          echo "Subtitles: $SUBTITLES"
          echo "Subtitle Style: $SUBTITLE_STYLE"
          echo "Transition Type: $TRANSITION_TYPE"
     

          # Build props JSON
          PROPS=$(jq -n \
            --argjson images "$IMAGES" \
            --arg audioUrl "$AUDIO_URL" \
            --argjson subtitles "$SUBTITLES" \
            --arg styleType "$SUBTITLE_STYLE" \
            --arg transitionType "$TRANSITION_TYPE" \
            '{
              images: $images,
              audioUrl: $audioUrl,
              subtitles: $subtitles,
              styleType: $styleType,
              transitionType: $transitionType
            }')

          echo "Constructed PROPS: $PROPS"

          npx remotion render VideoWithSubtitles \
            --props="$PROPS" \
            --output="rendered-video.mp4"

      - name: Upload Rendered Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-video
          path: "*.mp4"
          retention-days: 7

